### ISSUE TITLE
Add support for element selectors

### ISSUE THREAD

**Issue by biegehydra** [ilsadq/Blazor.DriverJs#2]
Currently the library either requires you to use a `DriverJsPopover` component or call `DriverJsPopover.Add(int step, PopoverModel model)` to register a step.

The add function is an awesome addition but requires you to use an `ElementReference`. This is a major drawback because when you are working with a component library like MudBlazor or something, you do not have access to the `ElementReference` of components. You also don't want to wrap a MudBlazor component is a `DriverJsPopover` because that messes with the styling because it gets wrapped in a span.

Instead, there should be a way to provide an ElementSelector `string` instead of a `ElementReference`. This would allow me to use this library with other component libraries like so.

```html
<DriverStore @ref="_driverStore" >
    <MudItem UserAttributes="@(new Dictionary<string, object?>() { { "id", "my-custom-id" } } )" md="6">
        @* Child Content *@
    </MudItem>
</DriverStore>

@code {
    private DriverStore? _driverStore;}
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _driverStore!.AddPopover(1, new PopoverModel()
            {
                ElementSelector = "#my-custom-id",
                Description = "description",
                Title = "title",
            });
            await _driverStore.StartDrive();
        }
    }
}
```

I was able to accomplish this locally by doing this.
#### PopoverModel.cs

```csharp
public class PopoverModel
{
    public ElementReference? Element { get; set; } // make nullable
    public string? ElementSelector { get; set; } // add this
    // Rest of code
}
```

#### index.js
```js
steps: model.steps.map(x => ({
    element: x.element ?? x.elementSelector, // coalesce the element selector
```

**The same solution could be applied to the `HighlightModel` as well.**

Something that could be done is to add a `[Parameter] public string? ElementSelector {get;set;}` on the `DriverJsPopover` popover component and then do. 
```
@if (string.IsNullOrWhiteSpace(ElementSelector)
{
    ﻿<span @ref="_ref" class="@Class">@ChildContent</span>
{
else
{
    @ChildContent
}
```
That way you can still use the DriverJsPopover in the razor and not have to register all the steps in the code block.

**Comment by ilsadq** [comment]
Hi thanks for the suggestion, I will try to add a convenient functionality for selecting items this weekend

**Comment by ilsadq** [comment]
Created a component that contextually returns an ID that you can pass to your component.

```
<DriverJsPopoverId Step="4" Title="Hello World">
     <img src="https://i.pinimg.com/736x/40/bb/da/40bbdac7db3945f95eb9cfe572d36ecd.jpg" alt=""
               id="@context">
</DriverJsPopoverId>
```

**Comment by ilsadq** [comment]
Created a component that contextually returns an ID that you can pass to your component.

```
<DriverJsPopoverId Step="4" Title="Hello World">
     <img src="https://i.pinimg.com/736x/40/bb/da/40bbdac7db3945f95eb9cfe572d36ecd.jpg" alt=""
               id="@context">
</DriverJsPopoverId>
```
